### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by dewey** [superturkey650/go-qbittorrent#2]
Hey,

I think there might be a bug in the POST request the login is doing. I had to refactor the following func with a small hack to get the login working again. It seems that there's a difference for qBittorrent between sending the parameters in the body like this or via the PostForm. I didn't fully dig in and just hacked it a bit to get it working. Just in case someone else is stumbling upon this. The current behaviours is that qBittorrent replies with "Fails." instead of "Ok." and a status code of 200 for both of them.

```
func (client *Client) post(endpoint string, opts map[string]string) (*http.Response, error) {
```

```
if endpoint == "login" && opts != nil {
		params := url.Values{}
		for k, v := range opts {
			params.Set(k, v)
		}
		body := bytes.NewBufferString(params.Encode())
		r, err := http.NewRequest("POST", client.URL+endpoint, body)
		if err != nil {
			return nil, wrapper.Wrap(err, "failed to build request")
		}
}
```

I also wrapped the existing section that assembles the PostForm the same login check.

```
	if endpoint != "login" && opts != nil {
		form := url.Values{}
		for k, v := range opts {
			form.Add(k, v)
		}
		req.PostForm = form
	}
```

**Comment by superturkey650** [comment]
Hey dewey,

qbittorrent had a large update from the version this was originally designed for. I'm currently working on these changes in the (dev)[https://github.com/superturkey650/go-qbittorrent/tree/dev] branch. It takes a lot of request changes and I'm still in progress on them. To use the wrapper for now, you can downgrade your qbittorrent version to the lowest accepted by this wrapper and it should still work.

**Comment by dewey** [comment]
Hey, thanks for that. Good to know. I'll keep watching the progress and downgrade my version in the mean time.

Thanks for the library!
